# Generated by Django 3.2.6 on 2021-08-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
