# Generated by Django 3.2.6 on 2021-08-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_template', '0002_alter_template_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
